name: DOA Takip Sistemi

on:
  workflow_dispatch:
    inputs:
      trigger_source:
        description: "Tetikleme kaynağı"
        required: false
        default: "manual"

  schedule:
    - cron: "*/5 * * * *"
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

permissions:
  contents: write

concurrency:
  group: doa-takip
  cancel-in-progress: false

jobs:
  doa-kontrol:
    runs-on